/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package viewQuanLyBenhNhan;

import controller.DAO;
import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;

/**
 *
 * @author QuangDuong
 */
public class viewThemBenhNhan extends javax.swing.JFrame {

    /**
     * Creates new form viewThemBenhNhan
     */
    public viewThemBenhNhan() {
        initComponents();
        this.setVisible(true); // Hien Frame
        this.setTitle("Patient manager"); // tieu de Frame
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup7 = new javax.swing.ButtonGroup();
        maBn = new javax.swing.JTextField();
        hoTen = new javax.swing.JTextField();
        tenKhoa = new javax.swing.JTextField();
        ngayXuatVien = new javax.swing.JTextField();
        loaiBenh = new javax.swing.JTextField();
        sdt = new javax.swing.JTextField();
        ngayNhapVien = new javax.swing.JTextField();
        diaChi = new javax.swing.JTextField();
        rbdNam = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        them = new javax.swing.JButton();
        back = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(0, 204, 153));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        maBn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maBnActionPerformed(evt);
            }
        });
        getContentPane().add(maBn, new org.netbeans.lib.awtextra.AbsoluteConstraints(253, 75, 210, -1));
        getContentPane().add(hoTen, new org.netbeans.lib.awtextra.AbsoluteConstraints(253, 113, 210, -1));
        getContentPane().add(tenKhoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(253, 153, 210, -1));

        ngayXuatVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ngayXuatVienActionPerformed(evt);
            }
        });
        getContentPane().add(ngayXuatVien, new org.netbeans.lib.awtextra.AbsoluteConstraints(254, 410, 210, -1));

        loaiBenh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loaiBenhActionPerformed(evt);
            }
        });
        getContentPane().add(loaiBenh, new org.netbeans.lib.awtextra.AbsoluteConstraints(253, 278, 210, -1));
        getContentPane().add(sdt, new org.netbeans.lib.awtextra.AbsoluteConstraints(253, 322, 210, -1));

        ngayNhapVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ngayNhapVienActionPerformed(evt);
            }
        });
        getContentPane().add(ngayNhapVien, new org.netbeans.lib.awtextra.AbsoluteConstraints(254, 366, 209, -1));
        getContentPane().add(diaChi, new org.netbeans.lib.awtextra.AbsoluteConstraints(253, 198, 210, -1));

        buttonGroup7.add(rbdNam);
        rbdNam.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        rbdNam.setForeground(new java.awt.Color(255, 255, 255));
        rbdNam.setText("Nam");
        rbdNam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbdNamActionPerformed(evt);
            }
        });
        getContentPane().add(rbdNam, new org.netbeans.lib.awtextra.AbsoluteConstraints(257, 235, -1, -1));

        buttonGroup7.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jRadioButton2.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton2.setText("Nữ");
        getContentPane().add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(336, 235, -1, -1));

        jPanel1.setBackground(new java.awt.Color(0, 204, 153));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Mã bệnh nhân");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Họ và tên");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Tên khoa");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Địa chỉ");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Giới Tính");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Loại Bệnh");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Số điện thoại");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Ngày nhập viện");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Ngày xuất viện");

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Thêm Bệnh Nhân");

        them.setBackground(new java.awt.Color(0, 204, 153));
        them.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        them.setForeground(new java.awt.Color(255, 255, 255));
        them.setText("Thêm");
        them.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                themMouseClicked(evt);
            }
        });
        them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                themActionPerformed(evt);
            }
        });

        back.setText("back");
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(back)
                        .addGap(80, 80, 80)
                        .addComponent(jLabel1)))
                .addContainerGap(160, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(them, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(193, 193, 193))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(back))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(them)
                .addGap(50, 50, 50))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void themActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_themActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_themActionPerformed

    private void maBnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maBnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maBnActionPerformed

    private void ngayNhapVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ngayNhapVienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ngayNhapVienActionPerformed

    private void ngayXuatVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ngayXuatVienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ngayXuatVienActionPerformed

    private void rbdNamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbdNamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbdNamActionPerformed

    private void loaiBenhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loaiBenhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loaiBenhActionPerformed

    private void themMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_themMouseClicked
        try{
            String nam = "Nam";
            String nu = "Nu";
            DAO d = new DAO();
            Connection conn = d.getConnection();
            PreparedStatement ps = conn.prepareStatement("insert into patient values(?,?,?,?,?,?,?,?,?,?)");
            ps.setString(1, maBn.getText());
            ps.setString(2, hoTen.getText());
            ps.setString(3, tenKhoa.getText());
            ps.setString(4, diaChi.getText()); 
            if(rbdNam.isSelected()){
                ps.setString(5, nam);
            } else{
                ps.setString(5, nu);
            }
            ps.setString(6, sdt.getText());
            ps.setString(7, loaiBenh.getText());
            ps.setObject(8, Date.valueOf(ngayNhapVien.getText()));
            ps.setObject(9, Date.valueOf(ngayXuatVien.getText()));
            String content ="- ngay nhap vien : "+ngayNhapVien.getText()+"  ngay xuat vien: "+ngayXuatVien.getText();
            ps.setString(10, content);
            
            int chk = ps.executeUpdate();
            if(chk > 0){
                JOptionPane.showMessageDialog(this, "Them thanh cong");           
            }
            else {
                JOptionPane.showMessageDialog(this, "Loi, moi ban nhap lai");
            }
        }catch(Exception ex){
            JOptionPane.showMessageDialog(this, "Trung ma benh nhan");   
        }
    }//GEN-LAST:event_themMouseClicked

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked
       this.dispose();
       new ql_benhNhan();
    }//GEN-LAST:event_backMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(viewThemBenhNhan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(viewThemBenhNhan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(viewThemBenhNhan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(viewThemBenhNhan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new viewThemBenhNhan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.ButtonGroup buttonGroup7;
    private javax.swing.JTextField diaChi;
    private javax.swing.JTextField hoTen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JTextField loaiBenh;
    private javax.swing.JTextField maBn;
    private javax.swing.JTextField ngayNhapVien;
    private javax.swing.JTextField ngayXuatVien;
    private javax.swing.JRadioButton rbdNam;
    private javax.swing.JTextField sdt;
    private javax.swing.JTextField tenKhoa;
    private javax.swing.JButton them;
    // End of variables declaration//GEN-END:variables
}
